### ISSUE TITLE
Not getting emails, error when clicking 'Send more docs now' button

### ISSUE THREAD

**Issue by akappen** [codetriage/docs_doctor#16]
I signed up right after RubyConf to get documentation emails from three projects but I have never received any emails. Today I tried the 'Send more docs now' button and it responds with an application error.

Let me know if there's anything I can do to help debug this.

**Comment by akappen** [comment]
I'll be around most of today, let me know how I can help.

**Comment by schneems** [comment]
There was a migration I was missing, ughhhh. I re-sent you some docs, did you get any email?

**Comment by akappen** [comment]
Yep,  just got an email. Thanks!

**Comment by schneems** [comment]
great! I'm going to close this issue. Please let me know if you stop getting emails again. Thanks for reporting :heart: i hadn't been sending emails to __anyone__ since december 17th
