### ISSUE TITLE
img/glyphicons-halflings-white.png is not yet added

### ISSUE THREAD

**Issue by olivierlacan** [codetriage/docs_doctor#28]
![image](https://cloud.githubusercontent.com/assets/65950/7556736/f90ab9e6-f74b-11e4-86a3-78ee0e674f59.png)

I don't even. :smile:

**Comment by prathamesh-sonpatki** [comment]
Yeah :smile:

**Comment by prathamesh-sonpatki** [comment]
Should be fixed now.
