### ISSUE TITLE
Can't edit or delete my account

### ISSUE THREAD

**Issue by olivierlacan** [codetriage/docs_doctor#29]
http://www.docsdoctor.org/users/182

I get a 500 on both actions.

**Comment by tejasbubane** [comment]
Hi @olivierlacan, there was an issue in the edit form. But the delete action works fine. I checked, the user  is being deleted. What I suspect is that because you have already assigned github permissions to docsdoctor, you get logged in automatically when you click on sign-in after deleting.

**Comment by jkrmr** [comment]
I'm seeing this same error, with both "Edit my account" and "Make account private".

Additionally, after returning to a non-500-error page and refreshing, I'm seeing the following notice:

![500-error](https://cloud.githubusercontent.com/assets/4433943/8842776/842cd61c-30cc-11e5-8401-a4b052c397dc.jpg)
![notice](https://cloud.githubusercontent.com/assets/4433943/8842777/84766ec6-30cc-11e5-909c-8a516821751f.jpg)

**Comment by prathamesh-sonpatki** [comment]
I think this will get solved after #30
